plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev' version '7.1.38'
}

version = mod_version
group = mod_group_id

base {
    archivesName = 'constructor-patch'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

repositories { }

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
