org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.1.3)
neo_version=26.1.2.95
mod_id=rftoolsbuilder
mod_name=Quantum Tools
mod_license=MIT
mod_version=3.0.6-dev.16
mod_group_id=mcjty.rftoolsbuilder
